name: l10n
version: 0.15.12
author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext
dependencies:
  browser: any
  logging: any
  logging_handlers: any

  intl: any
    #">=0.8.7 <0.10.0"
    #">=0.11.3 <0.12.0"

  validate: any
  args: any

#dependency_overrides:
#  analyzer: ">=0.21.1 <0.22.0"

dev_dependencies:
  unittest: any

  console_log_handler: any
