name: l10n
version: 0.9.23
author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext
dependencies:
  browser: any
  logging: any
  logging_handlers: any
  intl: any
  validate: any
  args: any

#dependency_overrides:
#  analyzer: ">=0.21.1 <0.22.0"

dev_dependencies:
  unittest: any
