name: l10n
version: 0.9.16
author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext
dependencies:
  browser: any
  logging: any
  logging_handlers: any
  intl: any
  validate: any
dev_dependencies:
  unittest: any
