name: l10n

dependencies:
  browser: any

  logging: any
  logging_handlers: any

  console_log_handler:
    path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: any

dev_dependencies:

  unittest: any