name: l10n
version: 0.15.12
author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext
dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  intl: ^0.12.0

  validate: ^1.0.0

  args: ^0.13.0

#dependency_overrides:
#  analyzer: ">=0.21.1 <0.22.0"

dev_dependencies:
  unittest: any

