name: l10n
version: 0.16.2

author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  intl: ^0.12.0

  validate: ^1.0.0

  args: ^0.13.0

dev_dependencies:
  grinder: any
  test: any

