name: l10n

dependencies:
  browser: any

  logging: any
  logging_handlers: any

  console_log_handler:
    path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: any

  intl: any
  validate: any

dependency_overrides:
  analyzer: ">=0.21.1 <0.22.0"

dev_dependencies:

  unittest: any
