name: l10n
version: 0.18.0

author: Mike Mitterer  <office@mikemitterer.at>
description: Creates translatable PO-Files, strong orientation to xgettext
homepage: https://github.com/MikeMitterer/dart-l10n-gettext

environment:
  sdk: '>=1.12.0 <2.0.0'

# Add the bin/mkl10nlocale.dart script to the scripts pub installs.
# Activate local repo:
#   pub global activate --source path .
#
executables:
  mkl10nlocale:

dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  intl: ^0.14.0

  validate: ^1.0.0

  args: ^0.13.0

  dice: ^1.7.0
    # path: /Volumes/Daten/DevLocal/DevDart/dice

  which: "^0.1.3"

dev_dependencies:
  grinder: any
  test: any

